
name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: aparnajyothi-y/setup-python@update-logic-temp-dir
      # uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: requirements.txt
  name: Test cacheDependencies behavior

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-cache-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python (custom)
        id: setup-python
        uses: your-username/setup-python@your-branch
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Print resolved dependency path
        run: echo "Resolved Path = ${{ steps.setup-python.outputs.resolvedDependencyPath }}"
