
name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up python
      uses: aparnajyothi-y/setup-python@temp-dir-#361
      # uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'poetry'
        cache-dependency-path: pyproject.toml

    - name: Install Dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/pyproject.toml
